### ISSUE TITLE
Inconsistent results between cafana v09_37_02_03 and v09_58_02

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/sbnanaobj#89] opened 2022-12-21 20:02 UTC
More info to come

**Comment by brucehoward-physics** [comment] 2022-12-21 23:10
People have recently noticed issues trying to use variables in newer versions of sbnana which seem to be tied to moving between v00.35 and v00.36 of SRProxy.

It was noticed by multiple people that trying to do things in the newer versions of sbnana (e.g. v09_58 era) was giving unexpected distributions in spectra with respect to previous versions. It realized that the difference seems to be coming more from sbnana and packages it includes than the CAF files themselves. For example, analyzing CAFs made in newer versions with the old sbnana was giving results more similar to before, and using older CAFs in newer sbnana was reproducing some of the unexpected changes in distributions.

As examples of the kind of unexpected changes, things like a hit purity variable in truth matching was suddenly giving a lot more entries closer to 0 purity than before. A plot on track length suddenly had a bump at ~320 cm (i.e. through-going cosmic muons) that wasn’t expected to be noticeable in the spectrum, and indeed doesn’t show when using an older release. Furthermore, selections were found to lead to asymmetry between the East and West cryostats (x<0 and x>0 respectively, x<0 - East - having more) when it is considerably more balanced analyzing the files with an older release of sbnana.

There is evidence from Ryan H. in Slack (cafana channel) that maybe not every variable is affected, e.g. he reported SRHit info being consistent across versions but that the associated SRSpacePoint information is inconsistent.

The changes in spectra presentation were traced by me to occur between v09_55_01 and v09_56_00 of sbnana, for which the main change seemed to be increasing SRProxy version from v00.35 to v00.36.

For more details see https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=29400

**Comment by brucehoward-physics** [comment] 2023-01-04 20:31
Above doc-db link updated to include a document exploring more about the changes between versions including when cutting on information at the slice level and when cutting on information including sub-slice (e.g. tracks) info.

I think the plot with the vertex X position, following up on a plot by Jacob L previously, is especially telling. The variable is at slice level, and when the cuts are only slice level no change is observed across versions. When sub-slice information is involved, then there are changes across the version v09_55_01 to v09_56_00 change.

**Comment by jedori0228** [comment] 2023-02-15 17:48
New release in SRProxy ([v00.39](https://github.com/CAFANA/SRproxy/tree/v00.39)) which has the fix for this issue. We should update this in the next release of sbnana(obj)

**Comment by brucehoward-physics** [comment] 2023-03-14 15:26
Hi -- I think the newest versions of sbnanaobj still have the old bugged SRProxy, is there a holdup in us adopting the fixed versions?

**Comment by jedori0228** [comment] 2023-03-14 15:39
I still don't see v00.39 under `/cvmfs/sbn.opensciencegrid.org/products/sbn/srproxy/`..

**Comment by brucehoward-physics** [comment] 2023-03-14 19:51
I missed that this was in `sbn` cvmfs -- asked instead to the #sbn_release_management channel on Slack.

**Comment by jedori0228** [comment] 2023-12-20 21:35
This issue is now resolved.

**Closed by jedori0228** 2023-12-20 21:35 UTC
Labels: bug
